#! /usr/bin/python3
# -*- coding: utf-8 -*-
# http://mystorycanbeatupyourstory.com/mix-match/
import random

adj = ["most adorable", "most adventurous", "most aggressive", "most agreeable", "alertest", "most amused", "angriest", "most annoyed", "most anxious", "most arrogant", "most ashamed", "most attractive", "averagest", "awfulest", "worst", "most beautiful", "most bewildered", "blackest", "bloodiest", "bluest", "bluest-eyed", "most blushing", "boredest", "bravest", "brightest", "calmest", "most charming", "cheerfulest", "cleanest", "clearest", "cloudiest", "clumsiest", "most colorful", "most comfortable", "most condemned", "most confused", "most cooperative", "most courageous", "craziest", "most flipped-out", "creepiest", "most crowded", "cruelest", "cutest", "most dangerous", "darkest", "most defeated", "most delightful", "most depressed", "most determined", "most disgusted", "distinctest", "most disturbed", "dizziest", "drabest", "dullest", "most eager", "most elated", "most elegant", "most embarrassed", "most enchanting", "most encouraging", "most energetic", "most enthusiastic", "most envious", "evilest", "most excited", "most exuberant", "fairest", "most faithful", "fanciest", "most fantastic", "fiercest", "filthiest", "finest", "foolishest", "most frantic", "friendliest", "most frightened", "funniest", "gentlest", "most glorious", "best", "most grieving", "grumpiest", "happiest", "healthiest", "most helpful", "most helpless", "most hilarious", "most homeless", "hungriest", "most hurt", "most ill", "most jealous", "most jittery", "jolliest", "laziest", "liveliest", "loneliest", "loveliest", "luckiest", "most mysterious", "nastiest", "naughtiest", "most nervous", "nicest", "nuttiest", "most obedient", "most obnoxious", "panickiest", "most perfect", "most pleasant", "proudest", "most repulsive", "scariest", "most selfish", "silliest", "most smiling", "most successful", "tensest", "most terrible", "most thoughtful", "most thoughtless", "most troubled", "most upset", "most uptight", "most victorious", "weariest", "wickedest", "wittiest", "worriedest"]
virtues = ["humanest", "most moderate", "justest", "most discerning", "most resilient", "most trustworthy", "fairest", "most integrous", "most responsible", "most empathic", "kindest", "most perceptive", "most diligent", "wisest", "friendliest", "most caring", "most compassionate", "most tactful", "most understanding", "most honest", "most appreciative", "lovingest", "most helpful", "most cooperative", "most serving", "most honourable", "most accountabile", "most determined", "most creative", "most considerate", "most modest", "joyfullest", "most purposeful", "most thoughtful", "most perseverant", "most hopeful", "sincerest", "most wondering", "most humble", "most assertive", "most reliable", "most courteous", "most truthful", "most mindful", "most decisive", "most flexibile", "openest", "most charitable", "noblest", "most dignified", "most respectful", "most devoted", "most confident", "most righteous", "most proactive", "most courageous", "strongest", "most forbearant", "most endurant", "most commited", "loyalest", "gentlest", "most steadfast", "most zealous", "most fidelitous", "most enthusiastic", "purest", "cleanliest", "most sacrificing", "trustingest", "most unifying", "most merciful", "most independent", "most orderly", "most optimistic", "most certain", "most faithful", "most patient", "most accepting", "most peaceful", "most tolerant", "most self-disciplined", "most fortitudinous", "simplest", "most gracious", "contentest", "most generous", "most beautiful", "serenest", "most grateful", "most excellent", "most thankful", "most awed", "most detached", "most prayerful" , "most forging", "cheerfulest", "most reverent"]

adj = list(set(adj + virtues)) # merge adj and virtues

person = ["accountant", "actor", "actuary", "agricultural and food scientist", "anthropologist", "architect", "archivist", "artist", "astronomer", "astronaut", "automotive mechanic", "baker", "banker", "barber", "beautician", "blacksmith", "bum", "bus driver", "car designer", "carpenter", "cashier", "chef", "chemist", "childcare worker", "chiropractor", "choreographer", "civil engineer", "clerk", "coach", "computer hardware engineer", "computer software engineer", "computer support specialist", "cost estimator", "court reporter", "curator", "dancer", "database administrator", "dental hygienist", "dental laboratory technician", "dentist", "dermatologist", "designer", "desktop publisher", "dietician", "disc jockey", "doctor", "drafter", "drummer", "economist", "electrical engineer", "electrician", "engineering technician", "environmental scientist", "farm manager", "farmer", "film directors", "financial analyst", "firefighter", "fisherman", "flight attendant", "funeral director", "hotel desk clerk", "human resources assistant", "interviewer", "investigator", "jeweler", "judge", "kindergarten teacher", "king", "landscape architect", "lawyer", "librarian", "loan officer", "mailman", "mathematician", "midwife", "mortician", "musician", "nurse", "optometrist", "orchestra conductor", "painter", "paralegal", "paramedic", "payroll clerk", "pediatrician", "pharmacist", "photographer", "physicist", "pilot", "plumber", "police officer", "politician", "prince", "princess", "private detective", "professional athlete", "psychologist", "public relations manager", "queen", "real estate agent", "receptionist", "recreation and fitness worker", "recreational therapist", "reporter", "roofer", "sailor", "school teacher", "seamstress", "secretary", "security guard", "singer", "social worker", "soccer coach", "statistician", "surgeon", "surveyor", "systems analyst", "tailor", "tax inspector", "taxi driver", "teacher", "therapist", "translator", "travel clerk", "truck driver", "university lecturer", "urban planner", "veterinarian", "violinist", "webmaster", "wedding planner", "writer", "zookeeper"]

print("Write about the " + random.choice(adj) + " " + random.choice(person) + ".")